config {
    type: "table",
    schema: "silver_" + dataform.projectConfig.vars.environment,
    name: "tb_reclame_aqui_clean",
    description: "Camadaa Silver: Dados Higienizados, deduplicados, anonimizados e validados",
    
    // Assertions garantes a qualidade dos dados
    assertions: {
        uniqueKey: ["id_reclamacao"],
        nonNull: ["id_reclamacao", "data_postagem", "empresa_alvo", "categoria_servico"]
    },
    tags: ["silver"]
}

SELECT
    id_reclamacao, 
    UPPER(TRIM(canal_origem)) AS canal_origem, 
    TRIM(empresa_alvo) AS empresa_alvo, 
    TRIM(categoria_servico) AS categoria_servico, 
    TRIM(titulo) AS titulo,

    -- Anonimação de dados email, telefone e cpf
    REGEXP_REPLACE(
        REGEXP_REPLACE(
            REGEXP_REPLACE(
                descricao_texto,
                r'\b\d{3}\.\d{3}\.\d{3}-\d{2}\b', '[CPF MASCARADO]'
            ),
            r'[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}', '[EMAIL MASCARADO]'
        ),
        r'\(?\d{2}\)?\s?\d{4,5}-\d{4}', '[TELEFONE MASCARADO]'
    ) AS descricao_texto,

    TRIM(replica_empresa_texto) AS replica_empresa_texto,

    -- Padronização de dados trim tira espaço vazio, upper deixa o texto maiusculo
    -- INITCAP deixza a primeira letra das palavras em maiusculo e o resto minusculo
    INITCAP(TRIM(cidade)) AS cidade,
    UPPER(TRIM(uf)) as uf,

    -- Conversão de tipo de dado safe_cast
    SAFE_CAST( data_postagem AS TIMESTAMP) AS data_postagem,
    UPPER(TRIM(status_resolucao)) AS status_resolucao,

    -- dados que não precisam ser tratados nessa etapa
    SAFE_CAST(nota_consumidor AS INT64) AS nota_consumidor, 
    SAFE_CAST(tempo_resposta_dias AS INT64) AS tempo_resposta_dias, 
    CAST(houve_reconsideracao AS BOOL) AS houve_reconsideracao, 
    UPPER(TRIM(score_prioridade_simulado)) AS score_prioridade_simulado,
    TRIM(tentativas_contato_previas) AS tentativas_contato_previas,

    -- metadado para auditoria de rastreabilidade de linhagem
    CURRENT_TIMESTAMP() AS data_processamento_silver

FROM
    ${ref("tb_reclame_aqui_raw")}

WHERE
    -- descartando dados inuteis
    id_reclamacao IS NOT NULL
    AND data_postagem IS NOT NULL